version: "3.7"
services:
  pocket-archiver:
    image: heussd/pocket-archiver
    volumes:
      - "${HOME}/data/:/data/:delegated"
    secrets:
      - POCKET_ACCESS_TOKEN
      - POCKET_CONSUMER_KEY
    depends_on:
      - fullfeedrss

        #  spoiler-vskm:
        #    image: heussd/spoiler-vskm
        #    volumes:
        #      - type: bind
        #        source: ${HOME}/data/news-retrieval/news.db
        #        target: /news.db
        #        consistency: cached
        #        read_only: true
        #      - type: bind
        #        source: ${HOME}/data/spoiler-vksm/
        #        target: /data/
        #        consistency: cached
        #        read_only: false
        #    secrets:
        #      - POCKET_ACCESS_TOKEN
        #      - POCKET_CONSUMER_KEY
        #
  newsboat:
    image: heussd/newsboat
    volumes:
      - '${HOME}/data/news-retrieval:/data/:delegated'
    depends_on:
      - fullfeedrss
    environment:
      - RELOAD_EVERY=6h

  fullfeedrss:
    restart: always
    image: "heussd/fivefilters-full-text-rss"
    volumes:
      - rss-cache:/var/www/html/cache"

  minidlna:
    image: cytomich/rpi-docker-minidlna
    restart: always
    network_mode: host
    volumes:
      - '/media/:/media/'
    environment:
      - MINIDLNA_FRIENDLY_NAME=maya
      - 'MINIDLNA_MEDIA_DIR=/media/'
        #  portainer:
        #    image: hypriot/rpi-portainer
        #    volumes:
        #      - '/var/run/docker.sock:/var/run/docker.sock'
        #    ports:
        #      - "9000:9000"
        #
volumes:
  rss-cache:

secrets:
  POCKET_ACCESS_TOKEN:
    file: ${HOME}/data/POCKET_ACCESS_TOKEN.txt
  POCKET_CONSUMER_KEY:
    file: ${HOME}/data/POCKET_CONSUMER_KEY.txt
