version: "3.7"
services:
  pocket-archiver:
    image: heussd/pocket-archiver
    volumes:
      - type: bind
        source: ${HOME}/data/pocket-archiver/
        target: /app/data/
        consistency: delegated 
        read_only: false
    secrets:
      - POCKET_ACCESS_TOKEN
      - POCKET_CONSUMER_KEY
    depends_on:
      - fullfeedrss

  newsboat-keyword-matcher:
    image: heussd/newsboat-keyword-matcher
    volumes:
      - type: bind
        source: ${HOME}/data/news-retrieval/news.db
        target: /news.db
        consistency: cached
        read_only: true
      - type: bind
        source: ${HOME}/data/spoiler-keyword-matcher/
        target: /data/
        consistency: cached
        read_only: false
    secrets:
      - POCKET_ACCESS_TOKEN
      - POCKET_CONSUMER_KEY

  newsboat:
    image: heussd/newsboat
    volumes:
      - '${HOME}/data/news-retrieval:/data/:delegated'
    depends_on:
      - fullfeedrss
    environment:
      - RELOAD_EVERY=12h

  fullfeedrss:
    restart: always
    image: "heussd/fivefilters-full-text-rss:3.8.1"
    volumes:
      - rss-cache:/var/www/html/cache"

  minidlna:
    image: cytomich/rpi-docker-minidlna
    restart: always
    network_mode: host
    volumes:
      - '/media/TIMMSTICK/media-copy-can-be-deleted/:/media/'
    environment:
      - MINIDLNA_FRIENDLY_NAME=maya
      - 'MINIDLNA_MEDIA_DIR=/media/'
        #  portainer:
        #    image: hypriot/rpi-portainer
        #    volumes:
        #      - '/var/run/docker.sock:/var/run/docker.sock'
        #    ports:
        #      - "9000:9000"
        #
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'letmein'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    #etwork_mode: host
    restart: unless-stopped

volumes:
  rss-cache:

secrets:
  POCKET_ACCESS_TOKEN:
    file: ${HOME}/data/POCKET_ACCESS_TOKEN.txt
  POCKET_CONSUMER_KEY:
    file: ${HOME}/data/POCKET_CONSUMER_KEY.txt
