version: "3.7"
services:
        #  pihole:
        #    labels:
        #      com.centurylinklabs.watchtower.scope: auto-update-plz
        #    image: pihole/pihole:latest
        #    ports:
        #      - "53:53/tcp"
        #      - "53:53/udp"
        #      - "67:67/udp"
        #      - "80:80/tcp"
        #      - "443:443/tcp"
        #    environment:
        #      TZ: 'Europe/Berlin'
        #      WEBPASSWORD: 'letmein'
        #      ServerIP: '192.168.178.10'
        #    # Volumes store your data between container upgrades
        #    volumes:
        #      - './etc-pihole/:/etc/pihole/'
        #      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
        #    dns:
        #      - 127.0.0.1
        #    # Recommended but not required (DHCP needs NET_ADMIN)
        #    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        #    #cap_add:
        #    #  - NET_ADMIN
        #    network_mode: host
        #    restart: unless-stopped
        #
  news-keyword-matcher:
    image: heussd/news-keyword-matcher
    labels:
      io.containers.autoupdate: registry
    environment:
      - "RELOAD_EVERY=30m"
    volumes:
      - type: bind
        source: ${HOME}/data/newsboat/news.db
        target: /news.db
        consistency: cached
        read_only: true
      - type: bind
        source: ${HOME}/data/keyword-matcher/
        target: /data/
        consistency: cached
        read_only: false


  news-retrieval:
    image: "heussd/news-retrieval"
    privileged: true # Required for sleep(!) on ARM Linux (?!)
    volumes:
      - '${HOME}/data/newsboat:/data/:delegated'
    depends_on:
      - fullfeedrss
    environment: 
      - FIVE_FILTERS_SERVICE=fullfeedrss
      - RELOAD_EVERY=5h
    command:
      - "/data/urls"
      - "/data/news.db"

      
  fullfeedrss:
    restart: always
    image: "heussd/fivefilters-full-text-rss:latest"
    labels:
      io.containers.autoupdate: registry
    volumes:
      - rss-cache:/var/www/html/cache"
    ports:
      - "8080:80"

        #  docker-logs-to-telegram:
        #    image: heussd/pipe-to-telegram
        #    volumes:
        #      - "/var/run/docker.sock:/var/run/docker.sock"
        #    environment: 
        #      - BOT_TOKEN=${BOT_TOKEN}
        #      - GROUP_ID=${GROUP_ID}



volumes:
  rss-cache:

